LegendApp/legend-list

example/app/(tabs)/flashlist.tsx
example/app/(tabs)/flatlist.tsx
example/app/(tabs)/index.tsx
example/package-lock.json
src/LegendList.tsx
src/types.ts

This pull request adds `ListHeaderComponent` and `ListFooterComponent` to `LegendList`.
* [`src/LegendList.tsx`](diffhunk://#diff-4accd310f7e3ff78e8fb07802542457bdb5e953f0c895d7d8b2668807c8c1884R50-R53): Added `ListHeaderComponent`, `ListHeaderComponentStyle`, `ListFooterComponent`, and `ListFooterComponentStyle` to the `LegendList` component, and rendered them conditionally. 
* [`src/types.ts`](diffhunk://#diff-c54113cf61ec99691748a3890bfbeb00e10efb3f0a76f03a0fd9ec49072e410aL2-R2): Updated `LegendListProps` type to include `ListHeaderComponent`, `ListHeaderComponentStyle`, `ListFooterComponent`, and `ListFooterComponentStyle` properties.

feat: add `ListHeaderComponent` & `ListFooterComponent`

---

example/app/(tabs)/index.tsx
example/package-lock.json
src/LegendList.tsx

The main changes involve adding a ref to the `LegendList` component and refactoring the `LegendList` component to use `forwardRef`.
From the way LegendList works, we could imagine this very simple change, allowing ScrollView methods to be used from a ref
Refactoring `LegendList` component:
* Added `ForwardedRef` and `forwardRef` imports in `src/LegendList.tsx`.
* Refactored `LegendList` to use `forwardRef` for better ref handling.

feat: allow ref usage with LegendList

---

example/app/(tabs)/index.tsx
example/app/renderItem.tsx
example/package-lock.json
src/LegendList.tsx

The `LegendList` component was experiencing type inference issues due to incorrect generic type handling in its declaration. This caused TypeScript errors when trying to use the component with specific data types, particularly around the `keyExtractor` prop.
Restructured the component's type declaration by moving the generic type assertion to the end of the component definition using an `as` type cast. This maintains proper type inference while allowing the component to work with generic data types as intended.

fix: Type Inference LegendList

---

src/ListComponent.tsx
src/types.ts

Currently, the list components (ListHeaderComponent, ListFooterComponent, and ItemSeparatorComponent) are typed as ReactNode. However, both React Native and FlashList support passing either a React component or a node.
This PR updates the types to have the same type definitions as React Native and FlashList.

fix: update list components types to match RN and Flashlist

---

example/app/(tabs)/_layout.tsx
example/app/(tabs)/index.tsx
example/app/(tabs)/more.tsx
example/app/initial-scroll-index/index.tsx
example/app/initial-scroll-index/renderFixedItem.tsx
example/components/ui/IconSymbol.tsx
src/LegendList.tsx
src/types.ts

This PR fixes adds possibility to use precise initialScrollIndex values. To have more precise calculation LegendList API was needed to be changed.
```
estimatedItemSize: number;
getEstimatedItemSize?: (index: number, item: T) => number;
```
Some additional changes were made:
- Added more tab with showcase different list options(good for the demo, I can delete it if needed).
- Removed effect to call handleScroll when initialScrollIndex is specified. initialContentOffset is passed directly to refState.current.scroll. This eliminates unneeded useEffect, and animation jerk upon initialisation.
- Fix issue with empty list on the Paper architecture.
Related issue: https://github.com/LegendApp/legend-list/issues/13

Fix handling of the initialScrollIndex in the list with fixed item sizes

---

example/app/(tabs)/_layout.tsx
example/app/_layout.tsx

I have found out, that after opening some other tabs(FlatList), "Legend List" tab's fps drops significantly. It looks like other tabs are still rendering in background. This PR enables freezing of inactive tabs, which should result in more accurate benchmarks.

[Example app] Freeze inactive tabs of the tab navigator

---

src/LegendList.tsx

Scroll is impossible when initial data height is 0 and data length changes later. It happens because scroll height is calculated only at init.
```
export default function HomeScreen() {
const listRef = useRef<LegendListRef>(null);
const [data, setData] = useState<Item[]>([]
);
useEffect(() => {
setTimeout(() => {
setData(sample);
}, 1000);
},[])
```
https://github.com/user-attachments/assets/d75425dd-fd54-4d3e-b99a-e992636142d1

fix: total scroll height calculation issue

---

example/app/(tabs)/more.tsx
example/app/chat-example/index.tsx

This PR adds very simple chat example to the more menu. This PR is mostly to fix https://github.com/LegendApp/legend-list/issues/31 , but along the way found few issues to list height calculation, and having this in more menu will help fixing those, and make regressions in list height calculation easier to find.
Also more menu display is improved.

Refine more menu, add chat example

---

example/app/(tabs)/index.tsx

Fixes display of the main tab list on Android:

fix: (example) display menu items on android

---

src/LegendList.tsx

Currently onEndReached onStartReached callbacks are triggered only once, and never reset. This PR adds reset code, so they can be reset when user scrolls down/up

fix: onStartReached, onEndReached handlers are triggered only once, and never reset

---

src/LegendList.tsx
src/types.ts

This PR adds timer to reset scroll velocity, when there was no scroll event for 500ms. It also prevents initial scroll to record velocity when using initial scroll index

fix: Improve scroll velocity handling, add timer to reset scroll velocity

---

src/LegendList.tsx

Fix to ensure onEndReached can fire again correctly when new data is appended, check #45

fix: add check to reset end flag on data append

---

example/app/cards-renderItem.tsx

- calling  refSwipeable?.current?.close(); on each recycle was very expensive, which made disadvantage for the LegendList in benchmarks .
- comment useViewability hooks for more accurate benchmarking.

fix: [example app] performance issue with closing swipable on each recycle

---

src/LegendList.tsx

Thanks for awesome list library! We were trying it out in our new app. It is working well so far. Noticed that scrolling to initial item does not trigger `onViewableItemsChanged` event (check below video). 
Quickly checked and found it is [returning](https://github.com/LegendApp/legend-list/blob/baf7a205031ffd5bd0c68e749fbf9d628aff64f7/src/LegendList.tsx#L328) early. I did not dig the entire logic but I think we meant to do explicit `null` checks here, because the value remains `0` and does not update. This change fixes it.
https://github.com/user-attachments/assets/dd514784-0710-4483-9ef3-d6e7fd9d9d2d

fix: trigger viewability event on scrolling to first item

---

src/Container.tsx

measure() api was not working properly

fix: Bring back old measurement method unstable_getBoundingClientRect

---

example/app/cards-flashlist/index.tsx
example/app/cards-renderItem.tsx
src/LegendList.tsx

During scroll we are spreading draw distance evenly to the top and to the bottom. But during fast scroll we are actually rendering invisible region oposite to the scroll direction. scrollExtra value mitigates the issue, but it doesn't really help with big draw distances.

fix:Improve scrolling window size

---

src/reanimated.tsx

This fix improves type inferrence for the reanimated version of the LegendList

fix: Better type inference for reanimated version of LL

---

src/LegendList.tsx

Some [APIs](https://github.com/react-navigation/react-navigation/blob/bddcc44ab0e0ad5630f7ee0feb69496412a00217/packages/native/src/useScrollToTop.tsx#L98) access functions like  `getScrollableNode` in an event, which in some edge cases gets triggered even if the ref is not initialised (ideally this should not happen, will need a PR in react navigation to add `null` check). However, to keep the feature parity with `FlatList` i think below change is still helpful. So this PR adds a change that is identical to `FlatList`'s [implementation](https://github.com/facebook/react-native/blob/b45851aecf9e22c6cbd3fc80bf5fa097a34d3d03/packages/react-native/Libraries/Lists/FlatList.js#L394).

fix: getScrollableNode access even when component is not mounted yet

---

src/LegendList.tsx

When using maintainVisibleContentPosition, the code was not properly checking if anchorElement was undefined, which could potentially cause runtime errors.
```
Warning: TypeError: Cannot read property 'coordinate' of undefined
```
Added an explicit undefined check for anchorElement before accessing its properties to ensure safer code execution.
- Added undefined check condition `anchorElement !== undefined` in the maintainVisibleContentPosition logic
- This prevents potential runtime errors when anchorElement is undefined
---
Version I use: 1.0.0-beta.11
environment: ReactNative 0.77.1 and New Architecture enabled (set maintainVisibleContentPosition, recycleItems enabled)

fix: Add undefined check for anchorElement in maintainVisibleContentPosition logic

---

package.json

Spotted in React Native Directory that npm package does not include meaningful description.
Update the package description. to the first sentence from README file, use GitHub shorthand for `repository` field, see:
* https://docs.npmjs.com/cli/v11/configuring-npm/package-json#repository

chore: update metadata in `package.json` file

---

src/Container.tsx
src/Containers.tsx
src/LegendList.tsx
src/ListComponent.tsx
src/reanimated.tsx
src/types.ts

Fixes https://github.com/LegendApp/legend-list/issues/113
Typing leadingItem correctly in internal components requires a generic type and some memo typing shenanigans. I could fallback to "any" if this additional complexity is unwanted.
I did not add trailingItem since FlatList docs only mention [leadingItem](https://reactnative.dev/docs/flatlist#itemseparatorcomponent). Supporting trailingItem would be a bit more work to find the next item and inject it in render.

Provide leadingItem to ItemSeparatorComponent

---

example/README.md
example/app.config.js

It's is important to have both version of the app on test devices

Add option to build old arch of the app

---

src/LegendList.tsx

If scroll destination is almost the same, avoid choosing new anchor element https://github.com/LegendApp/legend-list/issues/139

Add fix to avoid unneeded reanchorings

---

src/Container.tsx
src/LegendList.tsx
src/ListComponent.tsx
src/types.ts

This batches the size calculations from onLayout in a requestAnimationFrame. This has the benefit of reducing the number of times calculateItemsInView is called from size changing, at the expense of slightly delaying position adjustment.
I think we may want to have this behavior by default as *I think* it would generally increase scrolling performance and the case where multiple items change size. On the other hand it could increase gapping since it delays position updates by a frame. That might only be worse than now if a single item is laying out though?
If this generally works better we could default it to this, but have a way to control it:
1. A prop `batchLayouts` enabled by default, and can disable it
2. A function `syncLayout` (or a better name) which has a callback parameter and …

Batch layout

---

src/LegendList.tsx
src/types.ts

Ignore scroll events immediately following calcTotalSizesAndPositions, which fixes the flash when prepending items in onStartReached

Fix flash when prepending items in onStartReached

---

src/LegendList.tsx

https://github.com/LegendApp/legend-list/issues/158
Items with value 0 was not rendered by the list

Fix zero items issue

---

README.md
src/types.ts

Hey @jmeistrich,
I wanted to contribute somehow so I did a little work improving the ReadMe and I also added some tooltip comments in `types.ts` to  help with DX. It's just a start I suppose. 
I reworked the README example, but feel free to take it or leave it. I have always preferred as a Developer to just immediately see the usage (imports and all) right on the README. 
Thanks again,
Chris

Improve / Beautify README and Add MouseOver DX Tooltips to Properties and Ref Functions

---

example/app/cards-flashlist/index.tsx
example/app/countries-flashlist/index.tsx
example/components/Movies.tsx

Congratulations on the launch! I'm excited to see another list library in RN!
I looked at the codebase to understand why FlashList has so much blank area in your video [on x](https://x.com/jmeistrich/status/1915013704154054879).
FlashList's `drawDistance` is set to half of LegendList in all samples based on the assumption that we multiply them; however, we don't. FlashList uses [`ProgressiveListView`](https://github.com/Flipkart/recyclerlistview/blob/master/src/core/ProgressiveListView.tsx) that supports manipulation of drawDistance on initial load. We use that to prepare our recycling pool in advance (by [multiplying](https://github.com/Shopify/flash-list/blob/242ffce982cd0d482b4736ba7b16c854bd831a22/src/FlashList.tsx#L374) by 3). This is useful when item types are different. After the …

Use right drawDistance for FlashList

---

src/LegendList.tsx
src/ListComponent.tsx

Fixes #249 
LegendList removes paddingTop from style and stores the value in state. Then this padding is reapplied with PaddingAndAdjust component, which is rendered only if ListEmptyComponent is not provided. This PR fixes that and aligns with the behavior from the past -> https://github.com/LegendApp/legend-list/blob/c4de5253b3e5bfba37810ad04cebea403e0c00d5/src/ListComponent.tsx#L181
EDIT: It seems that this extra check was introduced to fix alignItemsAtEnd pushing ListEmptyComponent off the bottom. Instead I modified updateAlignItemsPaddingTop to ignore alignItemsAtEnd when the list is empty.

fix: PaddingAndAdjust for ListHeaderComponent
